### ISSUE TITLE
3.3.0 release causes semver breakage

### ISSUE THREAD

**Issue by astraw** [tiby312/tagger#25]
The recent relese (3.3.0) breaks backwards compatibility with 3.2.1 but is interpreted by cargo as backwards compatible. For example, this script compiles with 3.2.1:

```rust
fn main() {
    let mut wtr = tagger::new(tagger::upgrade_write(Vec::<u8>::new()));
    let _ = wtr.elem("svg", |d| {
        d.attr("xmlns", "http://www.w3.org/2000/svg")
            .attr("xmlns:xlink", "http://www.w3.org/1999/xlink");
    });
}
```

When `Cargo.toml` includes:

```toml
[dependencies]
tagger="=3.2"
```

Converting the version requirement to `tagger="3.2"` (removing the `=`), this example continues to compile if the `Cargo.lock` cache is maintained. However, upon doing `cargo update` or deleting `Cargo.lock`, tagger 3.3.0 is brought in because the tools assume it is "semver compatibile" with 3.2.1. However, the compilation will then fail with:

```
   Compiling tagger-test v0.1.0 (C:\Users\drand\Documents\src\rust-play\tagger-test)
error[E0599]: no method named `attr` found for enum `Result` in the current scope
 --> src\main.rs:5:14
  |
5 |             .attr("xmlns:xlink", "http://www.w3.org/1999/xlink");
  |              ^^^^ method not found in `Result<(), std::fmt::Error>`

error[E0308]: mismatched types
 --> src\main.rs:3:33
  |
3 |       let _ = wtr.elem("svg", |d| {
  |  _________________________________^
4 | |         d.attr("xmlns", "http://www.w3.org/2000/svg")
5 | |             .attr("xmlns:xlink", "http://www.w3.org/1999/xlink");
6 | |     });
  | |_____^ expected enum `Result`, found `()`
  |
  = note:   expected enum `Result<_, std::fmt::Error>`
          found unit type `()`

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `tagger-test` due to 2 previous errors
```

I think the correct solution here would be to yank 3.3.0 and re-release it as 4.0.0.

**Comment by tiby312** [comment]
Sorry about this. I followed @link2xt's advice and yanked those versions and released a 4.0.0

**Comment by astraw** [comment]
Thanks, works for me.
